### ISSUE TITLE
Extract full path of PDF file in creating a note

### ISSUE THREAD

**Issue by goballooning** [emacs-citar/citar-org-roam#12]
Dear, 

Is possible to extract the PDF file path from the BIB file in creating a node using `citar-open`?

I changed the line `"#+title: ${title}\n")` in function `citar-org-roam--create-capture-note` into `"#+title: ${citekey}\n\n${title}\n[[][PDF]]")`, and I would like to have a link to the PDF file as `[[full_file_path][PDF]]`.

I've been generating links manually using [Hook](https://hookproductivity.com), but think it could be automatic.

Thank you very much in advance,
Hongying

**Comment by bdarcus** [comment]
Not ATM. But maybe we could add a hook to make this possible in the future.

**Comment by goballooning** [comment]
I'm trying to put `[[full/path/to/foo.pdf][PDF]]` in the body. 
Though I'm not familiar with "capture templates", I would be glad to test this functionality in the future.

Thank you for your effort in implementing Org-roam, citar, and citar-org-roam.

Cheers,
P.S. Actually, I'm a Vim user, and just start using Emacs because of Org-roam.

**Comment by bdarcus** [comment]
Cool!

For capture templates, see org and org-roam documentation.

**Comment by bdarcus** [comment]
I think #32 and #33 addresses this. You can just configure `citar-org-roam-template-fields` to include the relevant file, and should be able to use it in your capture templates.
