### ISSUE TITLE
make full range of citar variables available in `org-roam-capture-templates`

### ISSUE THREAD

**Issue by lazzalazza** [emacs-citar/citar-org-roam#24]
I'm trying the new implementation of `citar-org-roam-capture-template-key`: it apparently breaks the `citar-has-notes` function, that doesn't find candidates anymore.  Here's the debugger backtrace:

```
Debugger entered--Lisp error: (void-function nil)
  nil()
  citar-has-notes()
  citar--format-candidates()
  citar-select-refs()
  byte-code("\300 C\207" [citar-select-refs] 1)
  command-execute(citar-open-notes)

```

Also, on startup I get an error that appears to be related to the issue:
`face-attribute: Opening directory: No such file or directory, /Users/test/org-roam`
My `citar-org-roam-subdir` is set to be `nil` (and the original org-roam directory does not match "/Users/test/org-roam").

Before this, I integrated org-roam by setting `orb-citar-source`'s  `:create` value  to `orb-citar-edit-note`. And in that case the code still works well.

**Comment by bdarcus** [comment]
Hmm ... I tested it yesterday, and ran into no such problems, nor can I see at first glance was could cause this.

What config are you using for this new see defcustom and the template?

cc @c1-g?

**Comment by lazzalazza** [comment]
Ok, I have managed to have it working by moving the whole Citar section in my config after the org-roam / org-roam-bibtex configuration. I am now encountering a different problem: after setting ` (setq citar-org-roam-capture-template-key "r")`, whenever I create a new note I am asked to insert the `author`, `citekey` and `file` values manually. Was this meant to work like that? Should I also set something else other than setting the `citar-org-roam-capture-template-key` value to get org-roam-bibtex automatically providing those values?

**Comment by bdarcus** [comment]
> Was this meant to work like that?

No; it should just work as expected, and did for me.

I'll try testing more today with my minimal init.

**Comment by bdarcus** [comment]
I just set it up on my minimal/experimental init, and had no problems. This is what I see when I go to create a new note.

![image](https://user-images.githubusercontent.com/1134/218312103-ebb7c252-92d4-4b03-8d4e-453d6fe1aedb.png)

**Comment by bdarcus** [comment]
Note that I have not tried random citar variables like `author` in the title; it may be one has to pass them in some form?

Any ideas @c1-g?

**Comment by lazzalazza** [comment]
Well, yes @bdarcus , that's the problem I'm encountering... I think the only sensible thing for me to do would be going back to invoking `orb-citar-edit-note`, and not calling the template directly via the new solution. At any rate, wouldn't it be nice to have a quick way to set `orb-citar-edit-note` as a substitute for `citar-org-roam-open-note`? Now, this can be achieved only by working on the `citar-notes-source` variable. Here's my current configuration:

```
 (citar-register-notes-source
   'orb-citar-source (list :name "Org-Roam Notes"
                           :category 'org-roam-node
                           :items #'citar-org-roam--get-candidates
                           :hasitems #'citar-org-roam-has-notes
                           :open #'citar-org-roam-open-note
                           :create #'orb-citar-edit-note
                           :annotate #'citar-org-roam--annotate))

  (setq citar-notes-source 'orb-citar-source)
```

This doesn't open the capture template for bibliography directly, but has the advantage of providing the template with all the right pre-processed fields via org-roam-bibtex.

**Comment by bdarcus** [comment]
Maybe, but:

- I'm not sure that belongs in this package, which is deliberately simpler than orb.
- I would still prefer to figure out how to achieve something similar, without having to add a bunch of code.

**Comment by c1-g** [comment]
I was able to reproduce the bug and moving citar's use-package declaration below org-roam-bibtex's fixed it. I don't know Emacs inner workings enough to explain it though.

@lazzalazza Can I see the capture template you use?

@bdarcus I foresaw some issues with keywords replacement and I think we can populate the `:info` plist by converting the output of `citar-get-entry` to a plist. The function `org-roam-bibtex` uses to expand its keyword is `orb--pre-expand-template`. 

I'm confused about what belongs in this package though. Is this package intended to be the simpler version of `org-roam-bibtex`?

**Comment by bdarcus** [comment]
> I'm confused about what belongs in this package though. Is this package intended to be the simpler version of org-roam-bibtex?

Simpler than orb for sure, but not really intended to be a "version" of it (which I never really used).

For this feature, I really only want to add it if the amount of code to add is small and straightforward, and it's also clear and consistent from the UX/config POV.

Does your question suggest we just consider it out-of-scope?

**Comment by lazzalazza** [comment]
@c1-g , here's my template! 
```
(setq org-roam-capture-templates
        '(("d" "default" plain
           "%?"
           :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+startup: content\n\n")
           :unnarrowed t)
          ("r" "bibliography reference" plain
           "%?
# Spazio per note di carattere generale\n\n* TODO Note al testo\n:PROPERTIES:\n:Custom_ID: %^{citekey}\n:NOTER_DOCUMENT: %^{file}\n:END:\n\n"
           :target
           (file+head "${citekey}.org" "#+title: ${author} - ${title}\n#+startup: content\n")
           :unnarrowed t)
          ))

``

**Comment by bdarcus** [comment]
> here's my template!

Though in this example, you don't need the full range of template variables; you can just use `citar-org-roam-note-title-template` to format that author and title bit.

Was there something you wanted beyond this, where you needed access to those variables somewhere else in the output?

Basically, what we have now works if you can define  `citar-org-roam-note-title-template`  so it's one continuous output.

Otherwise, of course, you can use the orb function instead, but then you bring with it all those dependencies.

**Comment by bdarcus** [comment]
I've revised the title for this issue to better clarify, since it's not a bug; was just a misunderstanding.

I think whether we add this additional functionality is an open question, though, per https://github.com/emacs-citar/citar-org-roam/issues/24#issuecomment-1427788144.

**Comment by bdarcus** [comment]
@lazzalazza today's commits adds that I think you were asking for, and which I've hoping to achieve without too much code. I think we achieved that, in fact.

**Comment by bdarcus** [comment]
Can any of you that see this take a look at https://github.com/emacs-citar/citar-org-roam/pull/44?

It builds on this functionality.
