### ISSUE TITLE
Double colons (::) in note titles cause org-roam links to break

### ISSUE THREAD

**Issue by JonathanReeve** [emacs-citar/citar-org-roam#56]
[The default value of `citar-org-roam-note-title-template` is `"${author editor} :: ${title}"`](https://github.com/emacs-citar/citar-org-roam/blob/e2cd111456d59fbf0b79e6684ad46c3686169f53/citar-org-roam.el#L37), but if that's the title of a note, a link to that note will result in a broken link, where if you try to follow the link, it fails with the message "No link found." I believe it has something to do with `::` being reserved syntax in Org for something like a definition, `key :: value`. Simply removing the double colon in the note title template fixes this: `(setq citar-org-roam-note-title-template "${author editor} : ${title}")`.

**Comment by bdarcus** [comment]
Thanks; fixed!
